/*
 * VocabularyBuilderPanel.java
 *
 * Created on April 23, 2009, 2:24 AM
 */
package hanzitrainer;

import java.awt.Component;
import java.awt.Font;
import java.util.Locale;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author  matthieu
 */
public class VocabularyBuilderPanel extends javax.swing.JPanel
        implements ListSelectionListener
{

    /** Creates new form VocabularyBuilderPanel */
    public VocabularyBuilderPanel(HanziDBscore database, HanziApplicationUpdater updater)
    {
        main_database = database;
        parent_app = updater;
        initComponents();
    }

    /** Creates new form VocabularyBuilderPanel and include the Cedict parser */
    public VocabularyBuilderPanel(HanziDBscore database, CedictParser cedict, HanziApplicationUpdater updater)
    {
        main_database = database;
        cedict_database = cedict;
        parent_app = updater;
        initComponents();
    }

    public void VocabularyBuilderUpdateDB()
    {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChineseLabel = new javax.swing.JLabel();
        PinyinLabel = new javax.swing.JLabel();
        EnglishLabel = new javax.swing.JLabel();
        ChineseTextField = new javax.swing.JTextField();
        EnglishTextField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        PinyinScroll = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        EnglishTranslationsListModel = new DefaultListModel();
        ETRenderer = new EnglishTranslationsRenderer();
        EnglishTranslations = new javax.swing.JList();

        setName("Form"); // NOI18N

        ChineseLabel.setText("Chinese"); // NOI18N
        ChineseLabel.setName("ChineseLabel"); // NOI18N

        PinyinLabel.setText("Pinyin"); // NOI18N
        PinyinLabel.setName("PinyinLabel"); // NOI18N

        EnglishLabel.setText("English"); // NOI18N
        EnglishLabel.setName("EnglishLabel"); // NOI18N

        ChineseTextField.setName("ChineseTextField"); // NOI18N
        if (cedict_database != null)
        {
            PinyinChooser = new PinyinChooserFrame(PinyinScroll,main_database, cedict_database);
            VocabularyBuilderUpdater = new VocabularyBuilderPanelUpdater(this, main_database, cedict_database);
        }
        else
        {
            PinyinChooser = new PinyinChooserFrame(PinyinScroll,main_database);
            VocabularyBuilderUpdater = new VocabularyBuilderPanelUpdater(this, main_database);
        }
        this.ChineseTextField.getDocument().addDocumentListener(PinyinChooser);
        this.ChineseTextField.getDocument().addDocumentListener(VocabularyBuilderUpdater);
        ChineseTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ChineseTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ChineseTextFieldFocusLost(evt);
            }
        });

        EnglishTextField.setName("EnglishTextField"); // NOI18N
        EnglishTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishTextFieldSaveButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Save"); // NOI18N
        SaveButton.setName("SaveButton"); // NOI18N
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset"); // NOI18N
        ResetButton.setDefaultCapable(false);
        ResetButton.setName("ResetButton"); // NOI18N
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        PinyinScroll.setName("PinyinScroll"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        EnglishTranslations.setModel(EnglishTranslationsListModel);
        EnglishTranslations.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        EnglishTranslations.setName("EnglishTranslations"); // NOI18N
        EnglishTranslations.addListSelectionListener(this);
        EnglishTranslations.setCellRenderer(ETRenderer);
        jScrollPane1.setViewportView(EnglishTranslations);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChineseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(PinyinLabel)
                            .addComponent(EnglishLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EnglishTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addComponent(PinyinScroll)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addComponent(ChineseTextField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ResetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChineseLabel)
                    .addComponent(ChineseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PinyinLabel)
                    .addComponent(PinyinScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnglishTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ResetButton)
                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(EnglishLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private class EnglishTranslationsRenderer extends JLabel implements ListCellRenderer
    {
        private int change_index;
        private DefaultListCellRenderer default_renderer;

        public EnglishTranslationsRenderer()
        {
            change_index = -1;
            default_renderer = new DefaultListCellRenderer();
        }

        public EnglishTranslationsRenderer(int index)
        {
            change_index = index;
            default_renderer = new DefaultListCellRenderer();
        }

        public void set_change_index(int index)
        {
            change_index = index;
        }

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus)
        {
            Component comp = default_renderer.getListCellRendererComponent(list,value,index,isSelected,cellHasFocus);
            setText(value.toString());
            if ((change_index != -1) && (index >= change_index))
            {
                System.out.println("index " + index + ", change " + change_index + ", text " +value.toString());
                setFont(comp.getFont().deriveFont(Font.ITALIC));
            }
            else
            {
                setFont(comp.getFont().deriveFont(Font.PLAIN));
            }

            return this;
        }
    }

private void ChineseTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChineseTextFieldFocusGained
// TODO add your handling code here:
    ChineseTextField.getInputContext().selectInputMethod(Locale.CHINA);

//EnglishTranslationsListModel.removeAllElements();
}//GEN-LAST:event_ChineseTextFieldFocusGained

    protected String getChineseTextField()
    {
        return ChineseTextField.getText();
    }

    protected void setEnglishTranslationsList(ArrayList<String> content)
    {
        int i;

        EnglishTranslationsListModel.removeAllElements();
        EnglishTranslationsListModel.addElement("[new]");
        for (i = 0; i < content.size(); i++)
        {
            EnglishTranslationsListModel.addElement(content.get(i));
        }
        EnglishTranslations.setSelectedIndex(0);
        EnglishTranslations.ensureIndexIsVisible(0);
    }

    protected void setEnglishTranslationsList(ArrayList<String> content, ArrayList<String> secondary)
    {
        int i;

        EnglishTranslationsListModel.removeAllElements();
        EnglishTranslationsListModel.addElement("[new]");
        for (i = 0; i < content.size(); i++)
        {
            EnglishTranslationsListModel.addElement(content.get(i));
        }
        for (i = 0; i < secondary.size(); i++)
        {
            EnglishTranslationsListModel.addElement(secondary.get(i));
        }
        ETRenderer.set_change_index(content.size()+1);
        EnglishTranslations.setSelectedIndex(0);
        EnglishTranslations.ensureIndexIsVisible(0);
    }

    private void SaveAction()
    {
        String english = EnglishTextField.getText();
        ArrayList<String> pinyin = PinyinChooser.get_pinyins();
        String hanzi_string = ChineseTextField.getText();
        ArrayList<String> hanzi = new ArrayList<String>();
        int i, listIndex;

        for (i = 0; i < pinyin.size(); i++)
        {
            if (!Pinyin.verify_pinyin(pinyin.get(i)))
            {
                return;
            }
        }

        for (i = 0; i < hanzi_string.codePointCount(0, hanzi_string.length()); i++)
        {
            int from = hanzi_string.offsetByCodePoints(0, i);
            int to = hanzi_string.offsetByCodePoints(0, i + 1);

            hanzi.add(hanzi_string.substring(from, to));
        }

        listIndex = EnglishTranslations.getSelectedIndex();

        if (listIndex == 0)
        {
            if (english.length() == 0)
            {
                return;
            }
            StringTokenizer english_tokens = new StringTokenizer(english, ",");

            while (english_tokens.hasMoreTokens())
            {
                String current_token = english_tokens.nextToken().trim();

                main_database.add_translation(current_token, pinyin, hanzi);
            }
        }
        else
        {
            if (english.length() == 0)
            {
                main_database.delete_translation(
                        (String) EnglishTranslationsListModel.getElementAt(EnglishTranslations.getSelectedIndex()), hanzi);
            }
            else
            {
                if (EnglishTranslations.getSelectedIndex() == 0)
                {
                    return;
                }
                if (english.length() == 0)
                {
                    return;
                }
                main_database.delete_translation(
                        (String) EnglishTranslationsListModel.getElementAt(EnglishTranslations.getSelectedIndex()), hanzi);
                main_database.add_translation(english, pinyin, hanzi);
            }
        }

        parent_app.update_database();

        EnglishTranslationsListModel.removeAllElements();
        ChineseTextField.setText("");
        EnglishTextField.setText("");
        ChineseTextField.requestFocus();
    }

private void EnglishTextFieldSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishTextFieldSaveButtonActionPerformed
    SaveAction();
}//GEN-LAST:event_EnglishTextFieldSaveButtonActionPerformed

private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
    SaveAction();
}//GEN-LAST:event_SaveButtonActionPerformed

private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
// TODO add your handling code here:
    ChineseTextField.setText("");
    EnglishTextField.setText("");
}//GEN-LAST:event_ResetButtonActionPerformed

private void ChineseTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChineseTextFieldFocusLost
// TODO add your handling code here:
    ChineseTextField.getInputContext().selectInputMethod(Locale.US);
}//GEN-LAST:event_ChineseTextFieldFocusLost

    public void edit_word(String to_edit)
    {
        ChineseTextField.setText(to_edit);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChineseLabel;
    private javax.swing.JTextField ChineseTextField;
    private javax.swing.JLabel EnglishLabel;
    private javax.swing.JTextField EnglishTextField;
    private javax.swing.JList EnglishTranslations;
    private javax.swing.JLabel PinyinLabel;
    private javax.swing.JScrollPane PinyinScroll;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel EnglishTranslationsListModel;
    private EnglishTranslationsRenderer ETRenderer;
    private HanziDBscore main_database;
    private HanziApplicationUpdater parent_app;
    private CedictParser cedict_database=null;
    private PinyinChooserFrame PinyinChooser;
    private VocabularyBuilderPanelUpdater VocabularyBuilderUpdater;

    public void valueChanged(ListSelectionEvent e)
    {
        int listIndex;
        String value;

        listIndex = EnglishTranslations.getSelectedIndex();
        if ((listIndex != 0) && (listIndex != -1))
        {
            value = (String) EnglishTranslationsListModel.getElementAt(EnglishTranslations.getSelectedIndex());
            EnglishTextField.setText(value);
        }
    }
}
